name: pr-develop-workflow
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out
      - run: go run math.go
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with: 
          commit-message: Updating develop with ${GITHUB_REF##*/} 
          branch: develop
          title: PR ${GITHUB_REF##*/} -> develop